FlightStrip/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from app1 import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', views.login),
    url(r'^app1/',include('app1.urls')),



]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),

# url(r'^account/',include('allauth.urls')),
 #
 # path("signup/", views.signup, name="account_signup"),
 #    path("login/", views.login, name="account_login"),
 #    path("logout/", views.logout, name="account_logout"),
 #    path("password/change/", views.password_change,
 #         name="account_change_password"),
 #    path("password/set/", views.password_set, name="account_set_password"),
 #    path("inactive/", views.account_inactive, name="account_inactive"),
 #
 #    # E-mail
 #    path("email/", views.email, name="account_email"),
 #    path("confirm-email/", views.email_verification_sent,
 #         name="account_email_verification_sent"),
 #    re_path(r"^confirm-email/(?P<key>[-:\w]+)/$", views.confirm_email,
 #            name="account_confirm_email"),
 #
 #    # password reset
 #    path("password/reset/", views.password_reset,
 #         name="account_reset_password"),
 #    path("password/reset/done/", views.password_reset_done,
 #         name="account_reset_password_done"),
 #    re_path(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
 #            views.password_reset_from_key,
 #            name="account_reset_password_from_key"),
 #    path("password/reset/key/done/", views.password_reset_from_key_done,
 #         name="account_reset_password_from_key_done"),

app1/urls.py
from django.conf.urls import url
from app1 import views
from django.urls import path
from app1.views import addFlightFromView


app_name='app1'


urlpatterns=[

          path('login/', views.login,name='default_login'),
          path('PrintPage/<int:id>/', views.PrintPage,name='PrintPage'),
          path('login/<msg>/', views.login,name='login'),
          path('mail/', views.mail,name='mail'),
          url(r'^register/', views.Register,name='register'),
          path('test/<message>/',views.test,name='test'),
          path('flightinfo/',views.flightinfo,name='flightinfo'),
          path('initialinfo/',views.main,name='initialinfo'),
          path('flightlist/',views.flightlist,name='flightlist'),
          path('uploadexcel/',views.uploadexcel,name='uploadexcel'),
          # path('deleteflight/', views.deleteflight, name='deleteflight'),
          path('flightUpdate/<int:id>/',views.flightUpdate,name='flightUpdate'),
          path('printStrip/',views.printStrip,name='printStrip'),
          path('getflightlist/',views.getflightlist,name='getflightlist'),
          path('delFlight/<int:pk>', views.delFlight.as_view(), name='delFlight'),
          url(r'^addFlightFromView/',addFlightFromView.as_view()),
          url(r'^ajax/checkCallSigh/$', views.checkCallSigh, name='checkCallSigh'),
          url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
          path('setting/', views.setting, name='setting'),
          path('aj_IDlist', views.aj_IDlist, name='aj_IDlist'),
          path('Flightinfoajax/',views.Flightinfoajax,name='Flightinfoajax'),
          path('autoUpdateflightlist/',views.autoUpdateflightlist,name='autoUpdateflightlist'),
          path('priniting/',views.printing,name='printing'),



]

app1/forms.py
from django import forms
from app1.models import user,flight,companyList,typeList,DaysOfweek,printingSetting
from datetimepicker.widgets import DateTimePicker
from bootstrap_datepicker_plus import DatePickerInput,TimePickerInput
from bootstrap_modal_forms.forms import BSModalForm




class loginForm(forms.ModelForm):
    class Meta:
        model=user
        fields=['username','password']

        widgets = {
            'password':forms.TextInput(attrs={'class':'datepicker','type':'password'}),
            }

    # 'EOBT':



class RegisterForm(forms.ModelForm):
    class Meta:
        model=user
        fields=['name','family','username','password','email','phone','job']

        widgets = {
            'job':forms.TextInput(attrs={'class':'fadeIn second','type':'text','id':'login','placeholder':'job'}),
            'job':forms.TextInput(attrs={'class':'hidden','type':'text','id':'login','placeholder':'job'}),
            }

class PassForm(forms.ModelForm):
    class Meta:
        model=user
        fields=['email']

class flightInfoForm(forms.ModelForm):
    CHOICES=[('Sunday','sun'),
         ('Monday','mon'),('Tuesday','tue'),
              ('Wednesday','wed'),('Thursday','thr'),
                   ('Friday','fri'),('Saturday','sat')]
    company=forms.ModelChoiceField(queryset=companyList.objects.all())
    type=forms.ModelChoiceField(queryset=typeList.objects.all())
    daysOfweek = forms.MultipleChoiceField(choices=CHOICES)

    # DayofWeek=forms.MultipleChoiceField(queryset=flight.objects.get(DayofWeek=CHOICES),widget = forms.CheckboxSelectMultiple)
    class Meta:
        model=flight
        fields=['company','flightNum','level','DepAirport','DesAirport','route','EOBT','type','dateFrom','dateTo','daysOfweek','delay','change','register']
        widgets = {
            'dateFrom':DatePickerInput(attrs={'class':'datepicker'}),
            'dateTo':DatePickerInput(attrs={'class':'datepicker'}),

            # 'EOBT':forms.TimeInput(attrs={'class':'timepicker'}),
            'EOBT':TimePickerInput(attrs={'class': 'timepicker'}),
            'company':forms.TextInput(attrs={'class':'form-control','placeholder':'company name...'}),
            'flightNum':forms.TextInput(attrs={'class':'form-control','placeholder':'flight number...'}),
            'level':forms.TextInput(attrs={'class':'form-control','placeholder':'level...'}),
            'route':forms.TextInput(attrs={'class':'form-control','placeholder':'route...'}),
            'type':forms.TextInput(attrs={'class':'form-control','placeholder':'type of aircraft...'}),
            'DepAirport':forms.TextInput(attrs={'class':'form-control','id':'pwd'}),
            'DesAirport':forms.TextInput(attrs={'class':'form-control','id':'pwd'}),
            'daysOfweek':forms.CheckboxSelectMultiple(attrs={'class':'form-check-input'}),
            'delay':forms.HiddenInput(),
            'change':forms.HiddenInput(),
            'register':forms.HiddenInput(),


        }
        # widgets = {
        #     'company': forms.TextInput(attrs={'class': 'form-control'}),
        # }

        # 'password':forms.TextInput(attrs={'placeholder':'Password'})}
class TypeForm(forms.ModelForm):
    class Meta:
        model=typeList
        fields=['type']
        widgets = {

            'type':forms.TextInput(attrs={'class':'form-control','placeholder':'type name...'}),
        }


class CompanyForm(forms.ModelForm):
    class Meta:
        model=companyList
        fields=['company']
        widgets = {

           'company':forms.TextInput(attrs={'class':'form-control','placeholder':'type name...'}),
        }
class delForm(BSModalForm):
    class Meta:
        model=flight
        fields=['company']
class settinprintForm(forms.ModelForm):
    class Meta:
        model=printingSetting
        fields='__all__'

app1/views.py
from django.shortcuts import render
from app1.forms import loginForm,RegisterForm,PassForm,flightInfoForm,CompanyForm,TypeForm,delForm,settinprintForm
from app1.models import user,typeList,companyList,flight,loggingTable,printingSetting
from django.shortcuts import redirect
from django.core.mail import send_mail
import random
from datetime import datetime,date,time,timedelta
import datetime
import openpyxl
import requests
from bs4 import BeautifulSoup
from urllib.request import urlopen
from bootstrap_modal_forms.generic import BSModalCreateView,BSModalDeleteView
from django.views.generic import FormView
from app1.mixins import AjaxFormMixin
from django.http import JsonResponse,HttpResponse
from django.contrib.auth.decorators import login_required
from django.db.models.signals import post_delete,post_save
import os,sys
import win32print
import win32ui
from PIL import Image,ImageDraw,ImageFont,ImageFilter,ImageWin
from django.db.models import Q
import io
import rx
import time
from django.core import serializers
import threading
<<<<<<< HEAD
from app1.functions import createSquack,sendpass,stripImage,printStripFunction,checktekarariUser,checktekarariEmail,checkmailexist
=======
from app1.functions import createSquack,sendpass,stripImage,printStripFunction,checktekarariUser,checktekarariEmail
>>>>>>> e570055d85d5d2da6b4e73db809294b9fdf52320

#saving actions
def Flightinfoajax(request):
    return render(request,'app1/Flight-info-ajax.html')
def aj_IDlist(request):
    quer = flight.objects.filter(company='IRA')
    datase = serializers.serialize('json',list(quer))
    data={'datase':datase}
    return JsonResponse(data, safe=False)

def setting(request):
    frm=settinprintForm
    ss=printingSetting.objects.get(id=1)
    if request.method=='POST' and 'sub' in request.POST:
        frm=settinprintForm(request.POST)
        if frm.is_valid():
            ss.minutesDiff=request.POST['minutesDiff']
            ss.printername=request.POST['printername']
            ss.save()
    return render(request,'app1/setting.html',{'frm':frm})

def save_flight(sender,instance,**kwargs):
    lg=loggingTable(actionName="saved flight record",dateAndTime=datetime.datetime.now())
    lg.save()
    print("logging")

post_save.connect(save_flight,sender=flight)


# formviews Functions
class addFlightFromView(AjaxFormMixin,FormView):
    form_class=flightInfoForm
    template_name='app1/Flight-info-ajax.html'
    success_url='/success/'



#
# Create your views here.

def mail(request):
    pssfrm=PassForm
    if request.method=='POST' and 'Recovery' in request.POST:
        pssfrm=PassForm(request.POST)
        if pssfrm.is_valid():
            email=pssfrm.cleaned_data['email']
            m=checkmailexist(email)
            if m==1:
                result=sendpass(email)
                return redirect('app1:login',msg="رمز به ایمیل مورد نظر ارسال شد")
            else:
                return render(request,'app1/PassRecovery.html',{'frm':pssfrm,'message':"ایمیل مورد نظر وجود ندارد"})

    return render(request,'app1/passRecovery.html',{'frm':pssfrm})

def flightUpdate(request, id):
    try:
        flt = flight.objects.get(pk=id)
    except flight.DoesNotExist:
        raise Http404("flights does not exist")
    if request.method=="POST" and 'updateBtn' in request.POST:
        flt.company=request.POST['company']
        flt.save()
        return redirect('app1:flightlist')


    dp=win32print.GetDefaultPrinter()
    # os.startfile("C:\\Users\\amiri\\Documents\\GitHub\\FlightStrips_django1\\app1\\templates\\app1\\printStrip.html","print")
    # os.startfile(r"C:\Users\amiri\Documents\GitHub\FlightStrips_django1\app1\templates\app1\details.html","print")
    return render(request, 'app1/details.html', {'flt': flt})

def uploadexcel(request):
    excel_data=""
    # if request.method=='POST' and 'btn5' in request.POST:
    #     for row in excel_data:
    #         for cell in row:
    #             flight.objects.create(company=row_data[row][0],
    #                               flightNum=row_data[row][1],
    #                               EOBT=row_data[row][2],
    #                               level=row_data[row][3],
    #                               DesAirport=row_data[row][4],
    #                               route=row_data[row][5],
    #                               dateFrom=row_data[row][6])

    if request.method=='POST' and 'btn4' in request.POST:
        excel_file = request.FILES["excelfile"]
        print(excel_file)

        wb = openpyxl.load_workbook(excel_file)

        worksheet = wb["Sheet1"]
        # print(worksheet["A5"].value)
        print(worksheet)


        excel_data = list()
        for row in worksheet.iter_rows():
            row_data = list()
            for cell in row:
                print(type(cell.value))
                row_data.append(str(cell.value))

            print(row_data[2])
            print(row_data[6])
            flight.objects.create(company=row_data[0],
                                  flightNum=row_data[1],
                                  EOBT=row_data[2],
                                  level=row_data[3],
                                  DesAirport=row_data[4],
                                  route=row_data[5],
                                  dateFrom=row_data[6])
                # b.save()
            excel_data.append(row_data)
        # for r in excel_data:
        #     for j in r:
        #         company=str(j.value)
        #         flightNum=str(j.value),
        #                               EOBT=datetime.time(14,5,00),
        #                               level=str(j.value),
        #                               DesAirport=str(j.value),
        #                               route=str(j.value),
        #                               dateFrom=datetime.datetime(2015,5,12))
        # print(excel_data[0][0])

    return render(request,'app1/upload.html',{"excel_data":excel_data})



def printStrip(request):
    flt=flight.objects.all()
    return render(request, 'app1/printStrip.html',{'flt':flt})



def test(request,message):
    return render(request,'app1/test.html',{'msg':message})

def login(request,msg='default'):
    frm=loginForm
    if msg=='default':
        m=""
    else:
        m=msg
    if request.method=='POST' and 'sub1' in request.POST:
        frm=loginForm(request.POST)
        if frm.is_valid():

            usr=frm.cleaned_data['username']
            pss=frm.cleaned_data['password']

            s,m=checklogin(usr,pss)
            print(m)

            if s==1:
                return redirect('app1:flightlist')
                # return render(request,'app1/main.html',{'username':m})
            else:
                print(m)
    return render(request,'app1/index.html',{'frm':frm,'message':m})

def checklogin(usr,pss):
    validate=0
    err=""
    try:
        q=user.objects.get(username=usr)
    except user.DoesNotExist:
        q=None
    if q is None:
        validate=0
        err="username is not exist or wrong!!!"
    else:
        if q.username==usr:
            if q.password==pss:
                validate=1
                err="you entered successfully!!!"
            else:
                validate=0
                err="username is correct but password is wrong"

    return validate,err

def validate_username(request):
    usr=request.GET.get('username',None)
    data={ 'username_exist':user.objects.filter(username__iexact=usr).exists(),}
    return JsonResponse(data)

def validate_company(request):
    flightNum = request.GET.get('flightNum', None)
    dat = {
        'flightnum_is_taken': flight.objects.filter(flightNum__iexact=flightNum).exists(),}
    return JsonResponse(dat)

def autoUpdateflightlist(request):
    dd=flight.objects.all()
    sd=serializers.serialize('json',dd)
    return JsonResponse(sd,safe=False)
    # return HttpResponse(flghtlist,content_type='application/json')
def flightinfo(request):
    # check callsign is Excist
    #
    week_days= ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday']
    dateDiff=''
    msg=''
    flightfrm=flightInfoForm
    cmp=companyList.objects.all()
    tp=typeList.objects.all()
    name='aaaa'
    e=''
    count=0
    day=""
    print("loading post.....")

    if request.method=='POST' and 'sbt' in request.POST:
        flightfrm=flightInfoForm(request.POST)
        print("loading flightfrm.....")
        # dates
        date1=request.POST.get("dateFrom")
        date2=request.POST.get("dateTo")
        print("date1 : "+str(date1))
        print("date2 : "+str(date2))
        l1=list(map(int, date1.split('/')))
        l2=list(map(int, date2.split('/')))
        print("splitting..."+str(l1))
        print("splitting..."+str(l2))

        dateFr = datetime.date(l1[2],l1[0],l1[1])
        dateT = datetime.date(l2[2],l2[0],l2[1])
        dateDiff=dateT-dateFr
        if (dateDiff.days>0 or dateDiff.days==0):
            print("> 0 or == 0" +"days:"+str(dateDiff.days))
            # end dates
            # do saving
            if flightfrm.is_valid():
                print("checking the validation....")
                for i in range((dateT -dateFr).days+1):
                    print("number of day "+str(i))
                    dateFrom=dateFr + datetime.timedelta(days=i)
                    print("current processing date: "+str(dateFrom))
                    daysselcted=request.POST.getlist('daysOfweek')
                    if week_days[dateFrom.weekday()] in daysselcted:
                        count=count+1
                        day=week_days[dateFrom.weekday()]
                        print(str(i)+" date:....>"+str(dateFrom)+"  daysofweek:...>"+week_days[dateFrom.weekday()])
                        print("****start saving the "+str(dateFrom)+" days of week....>"+week_days[dateFrom.weekday()])
                        # flightfrm.level=request.POST.get("level")

app1/templates/app1/flightlist.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquerylast.min.js' %}" type="text/javascript" language="javascript"></script>
    <!-- code Removed -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  <link rel="stylesheet" href="{% static 'css/Style2.css' %}">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- modal form -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- modal form -->
    <meta charset="utf-8">
    <title>AWZ_-_Developer's</title>
    <link rel="stylesheet" href="{% static 'css/Style.css' %}">

  </head>
  <body>
    <div class="header-up">
      <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a class="navbar-brand" href="#">||AWZ_Developer's||</a>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app1:default_login' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"></a>
          </li>
          <!-- Dropdown -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'app1:initialinfo' %}" id="navbardrop" data-toggle="dropdown">
              Initial information
            </a>
            <div class="dropdown-menu">
              <a >Company & Type</a>
            </div>
          </li>
          <!--end dropdown -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app1:flightinfo' %}">flight information</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app1:flightlist' %}">flight List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app1:uploadexcel' %}">Upload File</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app1:printStrip' %}">Print Strip</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app1:setting'%}">Setting</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app1:login' 'default' %}">Quit</a>
          </li>
        </ul>
      </nav>
    </div>

{% block contents%}
<!--search -->

    <div class="topsearch">
      <div class="container box">
        <form class="form-inline" method="get">
          <input id="company" type="text" class="form-control" name="company" placeholder="Call Sign">

          <div class="form-group">
            <label for="datefrom">DateFrom:</label>
            <input type="datetime" name="datefrom" id="datepicker" class="form-control">
          </div>
          <div class="form-group">
            <label for="dateto">Dateto:</label>
            <input type="datetime" name="dateto" id="datepicker1" class="form-control" >
          </div>
          <select class="form-control" id="sel1">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
          </select>

          <button type="submit" class="btn btn-info" name="srchBtn">search</button>
        </form>
        <div class="checkbox">
          <label><input type="checkbox" id="autoprint">Auto-Print?</label>
        </div>
        <br>
      </div>
    </div>

    <!-- end of search box -->
    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">

        </div>
      </div>
    </div>
    <br>
    <br>
        <!-- list start here -->
      <div class="container">
        <div>
          <form  method="POST">
           {% csrf_token %}
          <table id="tblFlightlist" class="table table-hover">
            <th>CallSign</th>
            <th>Type</th>
            <th>Departure</th>
            <th>Destination</th>
            <th>EOBT</th>
            <th>Date</th>
            <th>Route</th>
            <th>Register</th>
              {% for f in flights %}
            <tr class="flight-list-hover" id="tb1">
              <td>{{ f.company }} {{ f.flightNum }}</td>
              <td>{{ f.type }}</td>
              <td>{{ f.DepAirport }}</td>
              <td>{{ f.DesAirport }}</td>
              <td>{{ f.EOBT }}</td>
              <td>{{ f.dateFrom }}</td>
              <td>{{ f.route }}</td>
              <td>{{ f.Register }}</td>


              <td><button class="btn btn-xs btn-danger" type="button" data-toggle="modal" data-target="#confirmDelete" data-title="Delete User" data-message="Are you sure you want to delete this user ?"><img src="{% static 'image/delete.png' %}" alt=""></button></td>
              <td><a href="{% url 'app1:flightUpdate' f.id %}"><img src="{% static 'image/edit.png' %}" alt=""></a></td>
              <td><a href="{% url 'app1:printStrip'%}"><img src="{% static 'image/print.png' %}" alt=""></a></td>
              <td><a href="#" class="msge"><img  src="{% static 'image/message.png' %}" alt=""></a></td>
              <td> <input type="checkbox" name="checked" value="{{f.id}}">انتخاب </td>
              <div class="modal fade" id="confirmDelete" role="dialog" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
              <div class="modal-dialog">
              <div class="modal-content">
               <div class="modal-header">
                 <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                 <h4 class="modal-title"> حذف رکورد</h4>
               </div>
               <div class="modal-body">
                 <p> مطمئن هستید؟</p>
               </div>
               <div class="modal-footer">
                 <button type="button" class="btn btn-default" data-dismiss="modal">لغو</button>
                 <button type="submit" type="button" class="btn btn-danger" name="deleteBtn" value="{{f.id}}" id="confirm">پاک کردن</button>
               </div>
              </div>
              </div>
              </div>

            </tr>

            {% endfor %}

          </table>
          <input class="btn btn-success" type="submit" name="btn3" value="Send For Strip">
        </form>
      </div>
    </div>
    {% endblock %}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
    setInterval(function(){
      $("#tblFlightlist").empty();

      $.ajax({
        type:"GET",
        url:"{% url 'app1:autoUpdateflightlist'%}"
            }).done(function(data){
        var myv=JSON.parse(data);
        for(i=0;i<myv.length;i++){
        var columNames="<th>CallSign</th><th>Type</th><th>Departure</th><th>Destination</th><th>EOBT</th><th>Date</th><th>Route</th><th>Register</th>";
        var Printimg="<img src=../image/print.png>";
        var tdcompany="<td>"+myv[i]["fields"]["company"]+"</td>";
        var tdfilightNum="<td>"+myv[i]["fields"]["flightNum"]+"</td>";
        var tdtype="<td>"+myv[i]["fields"]["type"]+"</td>";
        var tdEOBT="<td>"+myv[i]["fields"]["EOBT"]+"</td>";
        var tddateFrom="<td>"+myv[i]["fields"]["dateFrom"]+"</td>";
        var tdDesAirport="<td>"+myv[i]["fields"]["DesAirport"]+"</td>";

        $("#tblFlightlist").append("<tr>"+tdcompany+tdfilightNum+tdtype+tdEOBT+tddateFrom+tdDesAirport+Printimg+"</tr>").css("cursor","hand");

            // alert(myv[1]["fields"]["company"]);
          }
       });
     },5000);
    // $(document).ready(function(){
    //   alert("hiiii");
    //   $("#tblFlightlist").append("<tr><td>hi</td><td>hello</td><td>khobi</td><td>hi</td><td>hello</td><td>khobi</td></tr>").css("cursor","hand")
    //   .on('click',function(){alert("cliii");});
    //   $.ajax({});
    // });
    // sending print instrunction

    setInterval(function(){
      if($("#autoprint").is(':checked'))
      {
     $.ajax({
       type:"GET",
       url:"{% url 'app1:printing'%}",
       success:function(data){
         // alert(data.status+" : "+data.flt);
       }
     });
   }
    },5000);
     $( function() {
       $( "#datepicker" ).datepicker({dateFormat: 'yy-mm-dd'});
       $( "#datepicker1" ).datepicker({dateFormat: 'yy-mm-dd'});

     });
     </script>

     <!-- modal -->
     <script src="{% static 'js/bootstrap.min.js' %}"></script>
     <script src="{% static 'js/jquery.min.js' %}"></script>
     <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
   <!-- You can alternatively load the minified version -->
     <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
     <script type="text/javascript">
       $(function () {

           $(".delete-flight").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
              });
           });
</script>
     <!-- modal -->

<script type="text/javascript">
serInterval(function(){
  $.ajax({
    method:"GET",
    url:"{% url 'app1:flightlist'%}",
    success:function(data){
      alert("goodddd");
    }

  });
},5000);
$(document).delegate(".msge","click",function(){
  console.log("messs");
});
  $('#confirmDelete').on('show.bs.modal', function (e) {
      $message = $(e.relatedTarget).attr('data-message');
      $(this).find('.modal-body p').text($message);
      $title = $(e.relatedTarget).attr('data-title');
      $(this).find('.modal-title').text($title);

      // Pass form reference to modal for submission on yes/ok
      var form = $(e.relatedTarget).closest('form');
      $(this).find('.modal-footer #confirm').data('form', form);
  });

  $('#confirmDelete').find('.modal-footer #confirm').on('click', function(){
      $(this).data('form').submit();
  });
</script>
  </body>
</html>

app1/templates/app1/mail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <p>mialed</p>
  </body>
</html>

app1/templates/app1/test.html
<!DOCTYPE html>
{% load  static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
{{ msg }}


  </body>
</html>